import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import classNames from 'classnames'
import Link from 'next/link'

export default function Home() {
  return (<>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className={styles.background}>
      <header className={styles.header}>
        <h1 className={styles.title}>
          Escuela Técnica Henry Ford
        </h1>

        <p className={styles.description}>
          Educación de exelencia, especialización electromecánica
        </p>

        <div className={styles.grid}>

          <Link href="/ingreso">
            <a className={styles.card}>
              <h2>Ingreso 2023 &rarr;</h2>
              <p>Información e instrucciones</p>
            </a>
          </Link>

          <Link href="/galeria">
            <a className={styles.card}>
              <h2>Galería &rarr;</h2>
              <p>Imágenes y videos</p>
            </a>
          </Link>

          <Link href="https://www.henryford.edu.ar/moodle/">
            <a className={styles.card}>
              <h2>Aula virtual &rarr;</h2>
              <p>Acceder a la plataforma</p>
            </a>
          </Link>

          <Link href="#novedades">
            <a className={styles.card}>
              <h2>Novedades &rarr;</h2>
              <p>
                Última información y eventos
              </p>
            </a>

          </Link>
        </div>
        <a className={classNames(styles.icon, styles['go-down-middle'])} href='#main'>
          <Image src="/arrow-down-navigate.svg" width="70px" height="70px" />
        </a>
      </header>
    </div>
    <div className={styles.container}>
      <main className={styles.main} id='main'>
        <div className={styles.container}>
          <a
            href="https://www.henryford.edu.ar/public/visita-virtual"
            className={classNames(styles.card, styles.big)}
          >
            <h2>Visita virtual &rarr;</h2>
            <p>Visita interactiva 360° para recorrer la escuela desde la computadora</p>
          </a>
        </div>
      </main>
      <footer className={styles.footer}>
        <a href="#">
          Escuela Técnica Henry Ford
        </a>
      </footer>
    </div>
  </>)
}
